import mongoose from "mongoose";

const clientSchema = mongoose.Schema({
    fName: String,
    lName: String,
    email: String,
    tel: String,
    gender: String,
    pregnancy: String,
    date:String,
    weight: Number,
    height: Number,
    job: String,
    city: String,
    sporDuringDiet: String,
    chronicIllness: String,
    usingMedicine: String,
    menopause: String,
    allergy: String,
    alcohol: String,
    cigarette: String,
    frequencySport:String,
    glassWater: String,
    useSugar: String,
    snackBrkfstToNoonTime:String,
    snackBrkfstToNoonFood:String,
    snackNoonToNightTime: String,
    snackNoonToNightFood: String,
    snackNightToSleepTime:String,
    snackNightToSleepFood:String,
    wakeupTime:String,
    firstSnackTime: String,
    breakfastTime:String,
    rushHour:String,
    workStartTime: String,
    dinnerTime:String,
    breakTime:String,
    secondSnackTime:String,
    lunchTime:String,
    sleepTime:String,
    offDaywakeupTime:String,
    offDayfirstSnackTime: String,
    offDaybreakfastTime:String,
    offDayrushHour:String,
    offDayworkStartTime: String,
    offDaydinnerTime:String,
    offDaybreakTime:String,
    offDaysecondSnackTime:String,
    offDaylunchTime:String,
    offDaysleepTime:String,
    wakeUpFood:String,
    breakfastFood:String,
    firstSnackFood:String,
    lunchFood:String,
    secondSnackFood:String,
    dinnerFood:String,
    nightTimeFood:String,
    offDaywakeUpFood:String,
    offDaybreakfastFood:String,
    offDayfirstSnackFood:String,
    offDaylunchFood:String,
    offDaysecondSnackFood:String,
    offDaydinnerFood:String,
    offDaynightTimeFood:String,
    
},{
    timestamps:true,
});

const Client = mongoose.model("Client", clientSchema);

export default Client;